-- Converted from hypr/.config/hypr/hyprland.conf (minimalist-clean branch) to the
-- Hyprland >= 0.55 Lua config format. See https://hypr.land/news/26_lua/ and
-- https://wiki.hypr.land/Configuring/Start/
--
-- NOT YET WIRED UP: Hyprland loads hyprland.lua INSTEAD of hyprland.conf if it
-- exists (checked once at startup) -- so hyprland.conf keeps working untouched
-- until you're ready to cut over. Rename/remove hyprland.conf (or move it aside)
-- once you've verified this file, then `hyprctl reload` / restart Hyprland.
--
-- See the NOTE comments below for spots that need your judgment call, not just
-- mechanical translation (search for "NOTE:").

------------------
---- MONITORS ----
------------------

hl.monitor({ output = "", mode = "preferred", position = "auto", scale = "auto" })
hl.monitor({ output = "eDP-2", mode = "2560x1600@165.0", position = "auto", scale = 1 })

-- NOTE: hyprland.conf sourced these two extra files, generated by an external
-- tool ("hyprmoncfg") that is NOT part of this repo and NOT audited here:
--   source = /home/maxime/.config/hypr/monitors.conf
--   source = ~/.config/hypr/hyprmoncfg-monitors.conf
-- Those are old hyprlang (.conf) syntax. `require()` in Lua-land loads .lua
-- modules, NOT hyprlang fragments -- there is no bridge between the two parsers.
-- Before you cut over, check whether hyprmoncfg can emit Lua instead (or
-- applies monitor layout live via `hyprctl` rather than writing static config).
-- Until then, DO NOT delete monitors.conf -- it is the only thing keeping your
-- per-monitor workspace layout applied. See notes at the bottom of this file
-- for what monitors.conf currently contains, translated for reference only.


---------------------
---- MY PROGRAMS ----
---------------------

local terminal    = "kitty"
local fileManager = "nautilus" -- dolphin
local menu        = "walker" -- was: wofi --show drun  #-i --allow-images
local browser     = "zen-browser"
local scripts     = os.getenv("HOME") .. "/.config/hypr/scripts"


-------------------
---- AUTOSTART ----
-------------------

-- NOTE: the original had a mix of `exec-once` (run once at startup) and bare
-- `exec` (old hyprlang re-runs bare `exec` on every config reload). The new
-- Lua autostart hook (`hl.on("hyprland.start", ...)`) only fires once, at
-- startup -- there is no documented Lua equivalent for "also re-run on every
-- reload" yet. All of the below are converted as run-once-at-startup, which
-- matches normal intent for daemons/services. If you relied on the
-- reload-retriggers-this behavior (e.g. to restart a crashed wl-paste
-- watcher on `hyprctl reload`), that behavior is not preserved here.
hl.on("hyprland.start", function()
    hl.exec_cmd("hypridle")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd(scripts .. "/set-wallpaper.sh")
    hl.exec_cmd("systemctl --user start elephant.service")
    hl.exec_cmd("walker --gapplication-service")
    hl.exec_cmd("hyprlock") -- lock just after autologin
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
end)


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")


-----------------------
---- LOOK AND FEEL ----
-----------------------

hl.config({
    general = {
        gaps_in  = 5,
        gaps_out = 20,
        border_size = 2,
        col = {
            active_border   = { colors = { "rgba(33ccffee)", "rgba(00ff99ee)" }, angle = 45 },
            inactive_border = "rgba(595959aa)",
        },
        resize_on_border = false,
        allow_tearing    = false,
        layout           = "dwindle",
    },

    decoration = {
        rounding       = 10,
        rounding_power = 2,
        active_opacity   = 1.0,
        inactive_opacity = 1.0,
        shadow = {
            enabled      = true,
            range        = 4,
            render_power = 3,
            color        = 0xee1a1a1a,
        },
        blur = {
            enabled  = true,
            size     = 3,
            passes   = 1,
            vibrancy = 0.1696,
        },
    },

    animations = {
        enabled = true,
    },
})

-- Curves used by the animation leaves below (bezier = NAME, X0,Y0,X1,Y1 -> points = {{X0,Y0},{X1,Y1}})
hl.curve("wind",   { type = "bezier", points = { {0.05, 0.9},  {0.1, 1.05} } })
hl.curve("winIn",  { type = "bezier", points = { {0.1, 1.1},   {0.1, 1.1} } })
hl.curve("winOut", { type = "bezier", points = { {0.3, -0.3},  {0, 1} } })
hl.curve("liner",  { type = "bezier", points = { {1, 1},       {1, 1} } })

hl.animation({ leaf = "windows",         enabled = true, speed = 6,  bezier = "wind",   style = "slide" })
hl.animation({ leaf = "windowsIn",       enabled = true, speed = 6,  bezier = "winIn",  style = "slide" })
hl.animation({ leaf = "windowsOut",      enabled = true, speed = 5,  bezier = "winOut", style = "slide" })
hl.animation({ leaf = "windowsMove",     enabled = true, speed = 5,  bezier = "wind",   style = "slide" })
hl.animation({ leaf = "border",          enabled = true, speed = 1,  bezier = "liner" })
hl.animation({ leaf = "borderangle",     enabled = true, speed = 30, bezier = "liner",  style = "once" })
hl.animation({ leaf = "fade",            enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "workspaces",      enabled = true, speed = 5,  bezier = "wind" })
hl.animation({ leaf = "specialWorkspace",enabled = true, speed = 5,  bezier = "wind",   style = "slidevert" })

-- "Smart gaps" for single/fullscreen windows
hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 8, gaps_in = 8 })
hl.workspace_rule({ workspace = "f[1]",   gaps_out = 8, gaps_in = 8 })

hl.window_rule({
    name  = "small-gaps-wtv1",
    match = { float = false, workspace = "w[tv1]" },
    border_size = 2,
    rounding    = 10,
})
hl.window_rule({
    name  = "small-gaps-f1",
    match = { float = false, workspace = "f[1]" },
    border_size = 2,
    rounding    = 10,
})

hl.config({
    dwindle = {
        -- pseudotile = true,  -- left disabled: was already commented out in hyprland.conf
        preserve_split = true,
    },
    master = {
        new_status = "master",
    },
})

hl.config({
    misc = {
        force_default_wallpaper = -1,
        disable_hyprland_logo   = true,
    },
})

-- Battery saving measures (kept as a second block, same as source, so the
-- override order -- vrr on, blur off -- matches the original file exactly)
hl.config({
    misc = {
        vrr = 1,
    },
    decoration = {
        blur = {
            enabled = false,
        },
    },
})


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "us",
        kb_variant = "",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",
        follow_mouse = 1,
        sensitivity  = 0.45,
        touchpad = {
            natural_scroll = false,
        },
    },
})

hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })

-- NOTE: "epic-mouse-v1" is Hyprland's own placeholder example device name --
-- both hyprland.conf source files (master and minimalist-clean) still had
-- this un-edited. It's inert unless you actually own a device by that name.
-- Kept here only for a faithful 1:1 port; consider deleting it.
hl.device({ name = "epic-mouse-v1", sensitivity = -0.5 })


---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER"

hl.bind(mainMod .. " + T", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd(browser))
hl.bind(mainMod .. " + Q", hl.dsp.window.close())
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + W", hl.dsp.window.float({ action = "toggle" }))

hl.bind(mainMod .. " + A", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + F", hl.dsp.exec_cmd(menu .. " -m files"))
-- NOTE: SUPER+V is bound TWICE in the source hyprland.conf (here, and again
-- just below to the wofi/cliphist picker). This is a pre-existing duplicate
-- bind in the .conf, not something introduced by this conversion -- the
-- second definition below is the one that will actually win. Flagging for
-- you to decide which one you actually want.
hl.bind(mainMod .. " + V", hl.dsp.exec_cmd(menu .. " -m clipboard"))
hl.bind(mainMod .. " + C", hl.dsp.exec_cmd(menu .. " -m bluetooth"))
hl.bind(mainMod .. " + P", hl.dsp.exec_cmd(menu .. " -m archlinuxpkgs"))
hl.bind(mainMod .. " + SHIFT + W", hl.dsp.exec_cmd(menu .. " -m menus:backgrounds"))
hl.bind(mainMod .. " + SHIFT + L", hl.dsp.exec_cmd(menu .. " -m menus:power"))

-- bind = $mainMod, S, togglesplit  -- left commented out, same as source (dwindle only)

hl.bind(mainMod .. " + V", hl.dsp.exec_cmd("cliphist list | wofi --conf ~/.config/wofi/config.clip -i | cliphist decode | wl-copy"))

-- Screenshot
hl.bind("PRINT", hl.dsp.exec_cmd("hyprshot -m window"))
hl.bind("SHIFT + PRINT", hl.dsp.exec_cmd("hyprshot -m region"))

-- Hyprlock
hl.bind(mainMod .. " + Alt + L", hl.dsp.exec_cmd("hyprlock"))

-- Move focus with mainMod + hjkl
hl.bind(mainMod .. " + h", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + l", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + k", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + j", hl.dsp.focus({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9], move window with mainMod + SHIFT + [0-9]
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key,         hl.dsp.focus({ workspace = i }))
    hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i, follow = true }))
end

-- Move active window silently to a workspace with mainMod + ALT + [1-9] (no 0/10 in source)
for i = 1, 9 do
    hl.bind(mainMod .. " + Alt + " .. i, hl.dsp.window.move({ workspace = i, follow = false }),
        { description = "move to workspace " .. i .. " (silent)" })
end

-- Special workspace (scratchpad)
hl.bind(mainMod .. " + S",         hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic", follow = true }))
hl.bind(mainMod .. " + Alt + S",   hl.dsp.window.move({ workspace = "special:magic", follow = false }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Volume
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+ && " .. scripts .. "/sys-notify.sh volume"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- && " .. scripts .. "/sys-notify.sh volume"),      { locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle && notify-send -h string:x-canonical-private-synchronous:sys-notify \"Mute Toggled\""), { locked = true, repeating = true })

-- Brightness
hl.bind("XF86MonBrightnessUp",   hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+ && " .. scripts .. "/sys-notify.sh brightness"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%- && " .. scripts .. "/sys-notify.sh brightness"), { locked = true, repeating = true })

-- Media (requires playerctl)
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next && " .. scripts .. "/sys-notify.sh media"),     { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous && " .. scripts .. "/sys-notify.sh media"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause && notify-send -h string:x-canonical-private-synchronous:sys-notify \"Media Toggled\""), { locked = true })

-- Lid switch handling: left disabled, same as source (kanshi profiles
-- currently do this job instead -- see kanshi/.config/kanshi/config)
-- hl.bind("switch:on:Lid Switch",  hl.dsp.exec_cmd("notify-send -a 'System' -i 'display' 'Lid Closed' 'Laptop display disabled'"), { locked = true })
-- hl.bind("switch:off:Lid Switch", hl.dsp.exec_cmd("notify-send -a 'System' -i 'display' 'Lid Opened' 'Laptop display enabled'"),  { locked = true })

-- Launch Steam Game Mode inside Gamescope
hl.bind(mainMod .. " + G", hl.dsp.exec_cmd("gamescope -f -e -W 2560 -H 1600 -r 120 -- steam -gamepadui"))


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

hl.window_rule({
    name  = "floating-apps",
    match = { class = "^(pavucontrol|better_control.py|blueman-manager|nm-applet|nm-connection-editor)$" },
    float = true,
})

-- NOTE: `size` as a table vs a "W H" string wasn't confirmed in the docs I
-- had available -- verify against `hl.window_rule` stubs/LSP before relying
-- on this one. Kept in the old string shape as the closest faithful port.
hl.window_rule({
    name  = "zoom-zen",
    match = { class = "^zen$" },
    size  = "200 200",
})

local suppressMaximizeRule = hl.window_rule({
    name  = "suppress-maximize-events",
    match = { class = ".*" },
    suppress_event = "maximize",
})

hl.window_rule({
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },
    no_focus = true,
})

hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },
    move  = "20 monitor_h-120",
    float = true,
})


-----------------------------------------------------------
-- Reference only: current monitors.conf (hyprmoncfg-owned) --
-----------------------------------------------------------
-- This is NOT active in this file (still hyprlang, still sourced separately
-- from hyprland.conf as noted at the top). Shown here translated so you can
-- see the shape once hyprmoncfg is updated to emit Lua, or ported by hand:
--
-- hl.monitor({ output = "desc:Dell Inc. DELL U2724DE 2N7XF84", mode = "2560x1440@59.95", position = "2610x-1440", scale = 1, sdr_min_luminance = 0.2, sdr_max_luminance = 80 })
-- hl.monitor({ output = "desc:Dell Inc. DELL U2724D 8HDVG84",  mode = "2560x1440@59.95", position = "0x-1440",    scale = 1, sdr_min_luminance = 0.2, sdr_max_luminance = 80 })
-- hl.monitor({ output = "desc:BOE 0x0BC9", disabled = true })
--
-- hl.workspace_rule({ workspace = "1", monitor = "desc:Dell Inc. DELL U2724DE 2N7XF84", default = true, persistent = true })
-- hl.workspace_rule({ workspace = "2", monitor = "desc:Dell Inc. DELL U2724D 8HDVG84",  default = true, persistent = true })
-- hl.workspace_rule({ workspace = "3", monitor = "desc:Dell Inc. DELL U2724DE 2N7XF84" })
-- hl.workspace_rule({ workspace = "4", monitor = "desc:Dell Inc. DELL U2724D 8HDVG84" })
-- hl.workspace_rule({ workspace = "5", monitor = "desc:Dell Inc. DELL U2724DE 2N7XF84" })
-- hl.workspace_rule({ workspace = "6", monitor = "desc:Dell Inc. DELL U2724D 8HDVG84" })
-- hl.workspace_rule({ workspace = "7", monitor = "desc:Dell Inc. DELL U2724DE 2N7XF84" })
-- hl.workspace_rule({ workspace = "8", monitor = "desc:Dell Inc. DELL U2724D 8HDVG84" })
-- hl.workspace_rule({ workspace = "9", monitor = "desc:Dell Inc. DELL U2724DE 2N7XF84" })
