source-file ~/.tmux.keybindings.conf
set -ga terminal-features ",*:RGB"

set -g mouse on # enable mouse

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# List of plugins
set -g @plugin 'catppuccin/tmux#v2.3.0'
set -g @plugin 'tmux-plugins/tmux-sensible' 
set -g @plugin 'tmux-plugins/tmux-yank'

set -g @plugin 'tmux-plugins/tmux-resurrect' # save tmux sessions
set -g @plugin 'tmux-plugins/tmux-continuum' # automatic restore tmux sessions
set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'
set -g @resurect-strategy-nvim 'session'

set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tpm'


# Basic setting for tmux
set -g default-terminal "tmux-256color"
set -g detach-on-destroy off     # don't exit from tmux when closing a session
set -g escape-time 0             # zero-out escape time delay
set -g history-limit 100000     # increase history size (from 2,000)
set -g set-clipboard on          # use system clipboard
set -g status-position top       # macOS / darwin style
set -g display-time 4000

set -g @continuum-restore 'on'   # automatic restore tmux sessions

# Appearance setting
set -g @catppuccin_flavor 'mocha' # latte, frappe, macchiato or mocha
set -g @catppuccin_window_status_style "rounded"

# Load catppuccin
# For TPM, instead use `run ~/.tmux/plugins/tmux/catppuccin.tmux`
run ~/.tmux/plugins/tmux/catppuccin.tmux
run ~/.tmux/plugins/tmux-battery/battery.tmux

# set vi-mode
set-window-option -g mode-keys vi

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
